src/Entity/Dish.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\DishRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: DishRepository::class)]
#[UniqueEntity('title', message: 'Ce plat existe déjà')]
class Dish
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    #[Assert\Length(min: 3, max: 50)]
    private ?string $Category = null;

    #[ORM\Column(length: 50)]
    #[Assert\Length(min: 3, max: 50)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    private ?string $description = null;

    #[ORM\Column]
    #[Assert\Positive()]
    #[Assert\LessThan(value: 1000)]
    #[Assert\NotNull()]
    private ?float $price = null;

    #[ORM\Column(type: 'datetime_immutable')]
    #[Assert\NotNull()]
    private ?DateTimeImmutable $updatedAt;

    public function __construct()
    {
        $this->updatedAt = new \DateTimeImmutable(); 
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategory(): ?string
    {
        return $this->Category;
    }

    public function setCategory(string $Category): self
    {
        $this->Category = $Category;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = new \DateTimeImmutable();

        return $this;
    }
}

src/Controller/DishController.php
<?php

namespace App\Controller;

use App\Entity\Dish;
use App\Form\DishType;
use Doctrine\ORM\EntityManager;
use App\Repository\DishRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Contracts\Cache\ItemInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Cache\Adapter\FilesystemAdapter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class DishController extends AbstractController
{
    /**
     * @param DishRepository $repository
     * @return Response
     */

    #[Route('/dish', name: 'dish.index', methods: ['GET'])]
    public function index(DishRepository $repository, Request $request): Response
    {
        /*$cache = new FilesystemAdapter();
        $data = $cache->get('dishes', function( ItemInterface $item) use ($repository) {
            $item->expiresAfter(15);
            return $repository->findAll(null);
        });*/ //cache not working like that, check later

        return $this->render('pages/dish/index.html.twig', [
            'dishes' => $repository->findAll(), //[] *Test message si données non récupérées*
        ]);
    }
}

templates/pages/dish/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Carte du restaurant
{% endblock %}

{% block body %}

	<div class="dishes-container">
		{% if not dishes is same as([]) %}
			<h1 class="h2-title">Voici le carte de notre restaurant</h1>
			<p>Le Chef Arnaud Michant aime passionnément les produits - et producteurs - de la Savoie.
				C’est pourquoi il vous propose au déjeuner comme au dîner une expérience gastronomique, 
				à travers une cuisine sans artifices avec ce goût de la qualité. Plus encore que ses 
				deux autres restaurants, Arnaud Michant le voit comme une promesse d’un voyage dans 
				son univers culinaire.
			</p>

			<div class="accordion d-flex flex-column" id="accordionExample">
				<div class="accordion-item">
					<h3 class="accordion-header" id="headingOne">
						<button class="accordion-button collapsed dropdown-toggle btn btn-primary btn-lg" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
							Les entrées
						</button>
					</h3>
					<div id="collapseOne" class="accordion-collapse collapse collapse-dishes" aria-labelledby="headingOne" data-bs-parent="#accordionExample" style="">
						<div class="accordion-body">
							{% for dish in dishes %}
								{% if dish.category == 'Entrée' %}
									<div class="dishes-content">
										<div class="dishes-maininfo">
											<p class="dish-title">{{ dish.title }}</p>
											<p class="dish-price">{{ dish.price }}
												€</p>
										</div>
										<p class="dish-desc">{{ dish.description }}</p>
									</div>
								{% endif %}
							{% endfor %}
						</div>
					</div>
				</div>
				<div class="accordion-item">
					<h3 class="accordion-header" id="headingTwo">
						<button class="accordion-button collapsed dropdown-toggle btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" style="font-size: 1.5rem; width: 100%; height: 60px; padding: 10px">
							Les plats
						</button>
					</h3>
					<div id="collapseTwo" class="accordion-collapse collapse collapse-dishes" aria-labelledby="headingTwo" data-bs-parent="#accordionExample" style="">
						<div class="accordion-body">
							{% for dish in dishes %}
								{% if dish.category == 'Plat' %}
									<div class="dishes-content">
										<div class="dishes-maininfo">
											<p class="dish-title">{{ dish.title }}</p>
											<p class="dish-price">{{ dish.price }}
												€</p>
										</div>
										<p class="dish-desc">{{ dish.description }}</p>
									</div>
								{% endif %}
							{% endfor %}
						</div>
					</div>
				</div>
				<div class="accordion-item">
					<h3 class="accordion-header" id="headingThree">
						<button class="accordion-button collapsed dropdown-toggle btn btn-primary btn-lg" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree" style="font-size: 1.5rem; width: 100%; height: 60px; padding: 10px">
							Les desserts
						</button>
					</h3>
					<div id="collapseThree" class="accordion-collapse collapse collapse-dishes" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
						<div class="accordion-body">
							{% for dish in dishes %}
								{% if dish.category == 'Dessert' %}
									<div class="dishes-content">
										<div class="dishes-maininfo">
											<p class="dish-title">{{ dish.title }}</p>
											<p class="dish-price">{{ dish.price }}
												€</p>
										</div>
										<p class="dish-desc">{{ dish.description }}</p>
									</div>
								{% endif %}
							{% endfor %}
						</div>
					</div>
				</div>
				<div class="accordion-item">
					<h3 class="accordion-header" id="headingFour">
						<button class="accordion-button collapsed dropdown-toggle btn btn-primary btn-lg" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour" style="font-size: 1.5rem; width: 100%; height: 60px; padding: 10px">
							Les boissons
						</button>
					</h3>
					<div id="collapseFour" class="accordion-collapse collapse collapse-dishes" aria-labelledby="headingFour" data-bs-parent="#accordionExample" style="">
						<div class="accordion-body">
							{% for dish in dishes %}
								{% if dish.category == 'Boisson' %}
									<div class="dishes-content">
										<div class="dishes-maininfo">
											<p class="dish-title">{{ dish.title }}</p>
											<p class="dish-price">{{ dish.price }}
												€</p>
										</div>
										<p class="dish-desc">{{ dish.description }}</p>
									</div>
								{% endif %}
							{% endfor %}
						</div>
					</div>
				</div>
			</div>

		{% else %}
			<h1>Il n'y a pas encore de plats dans la carte</h1>
		{% endif %}
	</div>
{% endblock %}